### ISSUE TITLE
The add-on stopped working.

### ISSUE THREAD

**Issue by finnlogin** [cardinalby/memrise-audio-uploader#1]
Good day!

I just wanted to let you know that the add-on stopped working a few days ago and there is no button to upload audios at the moment. I would appreciate if you could fix the issue as your add-on is really of help!

Thank you

PS I checked working both in Firefox and Chrome.

**Comment by cardinalby** [comment]
Hi! Could you provide your browser and extension versions?
For me version 1.1.30 still works on Chrome 84.0.4147.105

**Comment by MusaGus** [comment]
Hello!
Actually, I have the same problem. 
For me ver. of extension: 1.1.30 doesn't work neither in chrome (Version 84.0.4147.105 (64-bit)), nor in Firefox 79.0 (64-bit). 
OS: Win10 Pro 1909

**Comment by finnlogin** [comment]
> Hi! Could you provide your browser and extension versions?
> For me version 1.1.30 still works on Chrome 84.0.4147.105

I have the same versions of my browser and extension. Unfortunately, it doesn't work for me. My operating system is OSX 10.14.6.

**Comment by finnlogin** [comment]
> Chrome

Could I ask to comment on this? Perhaps you can advise something to solve the issue?

**Comment by vitran1987** [comment]
Hi @cardinalby ,
URL has changed from www.memrise.com to app.memrise.com. This cause your script stop working (the Upload button is no longer displayed)

**Comment by cardinalby** [comment]
@MusaGus @vitran1987 
Sorry for the delay, we have a revolution here, in Belarus :)

@finnlogin
Thanks for the investigation, I changed the target URL to `app.memrise.com`, the new version will be published soon

**Comment by cardinalby** [comment]
Fixed version 1.2.0 was published on Chrome Webstore and Firefox Addons. It also includes minor changes: now button is called "Upload audios" and placed at the bottom of the page near "Save and continue" (to avoid scrolling to the top each time for big courses)

Please check it works for you.

**Comment by vitran1987** [comment]
It works great. Thanks a lot.
