### ISSUE TITLE
Suggestion/Issue

### ISSUE THREAD

**Issue by AlizeeFR** [cardinalby/memrise-audio-uploader#2]
I have IVONA and Nuance Vocalizers I like which I bought from HARPO (harposoftware . com/en/) and I would like to be able to use them to generate the TTS files for my course, but there is no option to do so. Do you think you might be able to add this feature into the add-on? I'm asking because SoundOfText does not have the languages I am studying, but I have my own IVONA voices for them. Thank you

**Comment by cardinalby** [comment]
Hi! Thanks for the interest in the project.

As I understand, mentioned vocalizers are not cross-platform (Windows only), and have no web API accessible from a browser. I can't exclude the possibility that the integration is possible, but it would require an additional adapter desktop application to be installed on the user's machine to interact with the vocalizer software. As I can see, this software has no available stable API, and as I can see it will take a lot of work for both investigations of that possibility, implementation, and further support of such plugin.

The extension is non-commercial and unfortunately, at the moment I have no capacity for working on that. 
But if you will be able to implement it in a fork then feel free to contact me to discuss/review and accept PR.
