### ISSUE TITLE
feature request: include button on database tab on chrome extension

### ISSUE THREAD

**Issue by cbarina** [cardinalby/memrise-audio-uploader#4]
This is a game-changing app! So great :) 

Small request - the button is so useful on the Levels tab, but can it be also shown on the database tab? Sometimes I realize after I've entered words that I have small errors (accents, order of words, etc.) and my workflow is to search for the item in the database and update there. It would be great to then delete the related audio and re-generate it/attach it from that interface as I have lots (30+) levels and don't always know where it is exactly and thus what level to expand and update.

**Comment by cardinalby** [comment]
Hi! Thanks for the feedback. 

Your suggestion looks pretty reasonable. Unfortunately, I don't have the capacity for this now, but I promise to have a look at it later. Meanwhile, you are welcome to create a pull request if you decide to implement it by yourself.

**Comment by cardinalby** [comment]
Hi @cbarina ! I have implemented the feature you requested  in version 1.3.0. It's already published on Firefox Addons and Chrome Web Store.

Please check it out and let me know if it works as expected

**Comment by cardinalby** [comment]
@cbarina can I close the issue?

**Comment by cbarina** [comment]
Hi! Thanks for following up - just checked it out and it works great! I'll close it out.
