### ISSUE TITLE
Custom audio choice?

### ISSUE THREAD

**Issue by staceyb5** [cardinalby/memrise-audio-uploader#5]
Sorry if this is the wrong place to ask this. You have created an awesome script for auto uploading audio. It is actually the only one I've found and I've search for a long time. I have been using Azure Cognitive Services Text to Speech for Anki cards, but I much prefer MemRise. I was wondering if there was some way to use my own option of where to pull the text to speech from in your script? I think this would be a great feature and it would be the MemRise equivalent of AwesomeTTS (anki addon). Again, sorry if this is the wrong place or an inappropriate request, I'm not familiar with github etiquette.

**Comment by cardinalby** [comment]
Hi! Thanks for the feedback. I agree, having multiple configurable audio sources would be great. 
Unfortunately, I have no capacity for implementing it: current code needs to be refactored and some amount of new code should be added and supported in the future. It's a free and non-commercial project and I just don't have capacity in the near future :( 
If you can implement it, your PRs are welcome!

**Comment by staceyb5** [comment]
Thank you so much for the response!
