### ISSUE TITLE
Rows are skipped

### ISSUE THREAD

**Issue by Arosasuke** [cardinalby/memrise-audio-uploader#6]
When pressing the button, some of the rows are skipped, though initially, the message says "Auto Uploading", the first circle turns red and the audio does not get uploaded.
![image](https://user-images.githubusercontent.com/131486003/233712139-f95f313c-e7e3-478e-8f0b-6c8da8b5108d.png)
![image](https://user-images.githubusercontent.com/131486003/233712155-46ce7a89-2493-4964-8ef2-6901ff9d7a0f.png)

**Comment by cardinalby** [comment]
Hi! Thanks for creating the issue. 

The extension uses Google Translator API to get audios and requests can be throttled and declined in some cases out of my control.

Please look at the browser console and inspect the errors. Also paste here English text of the rows that cause the problem
