### ISSUE TITLE
it's can not upload file each row

### ISSUE THREAD

**Issue by trantrinhquocviet** [cardinalby/memrise-audio-uploader#7]
Hey, when i click button upload audio, it's not working.

i show my evident:
it show case 'download': return '🔴⚪'; but can not upload  case 'upload': return '⚫🔴';
![image](https://github.com/cardinalby/memrise-audio-uploader/assets/26039338/382b6258-2fbc-459c-832c-61d226855d49)

permission i setup on chrome: 
![image](https://github.com/cardinalby/memrise-audio-uploader/assets/26039338/570d5a06-992e-497a-a09a-b73977e905a9)

But, some word can upload:
![image](https://github.com/cardinalby/memrise-audio-uploader/assets/26039338/2ec3db0e-ea7c-400a-86b5-8669b58d1c60)

Hey, my question. Do you have limit with you dictionary?

**Comment by cardinalby** [comment]
It uses google translator API and can reach some limits if you use it a lot. Regarding the size of a course, I haven't faced any problems.

Can you try to collect some errors from the browser console (press F12)?

**Comment by trantrinhquocviet** [comment]
Yes, i see. How many times a day can you use it? and i can donote to you upgrade new package google translator API.
I see another API text to speech. https://rapidapi.com/search/text%20to%20speech
you can check it out.

**Comment by trantrinhquocviet** [comment]
my console:
![image](https://github.com/cardinalby/memrise-audio-uploader/assets/26039338/50de8fc6-5e39-4b70-992c-7a33cae1c851)

**Comment by trantrinhquocviet** [comment]
Thanks for your support. i found the reason. Just enable https://translate.google.com/ in setup
![image](https://github.com/cardinalby/memrise-audio-uploader/assets/26039338/9b7385f8-7b9f-42ea-9baa-13443850cf27)
